logging:
  level:
    com.devquest: INFO

spring:
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}?sslmode=require
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    locations: classpath:db/migration

server:
  error:
    include-stacktrace: never
    include-message: never

storage:
  datasource:
    core:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://${DB_HOST}/${DB_NAME}?sslmode=require
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      maximum-pool-size: 10
      minimum-idle: 0
      connection-test-query: SELECT 1
